/**
 * @author Kate
 */

var grammars = {
 	
    scifi : {
	"origin": ["#word#: #code#. Definition: #definition#"],
"code":["#co#, #de#"],
"co":["Adjective","Noun","Adverb","Expletive","Gerund", "Interjection", "Quantum-Verb"],
"de":["Base-Human","#race# #quasi#English","#planet#-Creole", "#planet# Esperanto", "#race# #planet# Slang", "#race# #planet# Colloquial", "#race# #planet# English", "Alien", "#country# MindMeld","#country# High Tongue", "Asian #quasi#Bahasa","#race# Creole","post-Singularitarian #country#", "Necrotongue A", "Necrotongue B", "God Emperor High Speech", "Unnamed Language #n##n##n##n##n#", "#country# Creole", "Future #country# #quasi#Language, Circa #n##n##n##n# C.E", "Nomadic #country# Variant", "Space #country#", "Post-Singularity #country#", "Uplifted #country#"],
"race": ["black", "Caucasian", "trader", "Spacer", "lo-grav", "pidgin", "South-Islander", "Asian"],
"quasi":["quasi-","semi-","","Evolved ", "Dark ", "Mental ", "Neural ", "Decentralized ","ex-","United "],
"planet": ["Ganymedian", "Martian", "Venutian Clouder", "Mercury City", "Ceres Alliance", "Io Republic", "Deep Space Neptune", "Belter","Matrioshka MindPlace", "Dyson Swarm Station No.#n##n##n##n##n#", "Ionian", "Ceres", "Oort", "Pluto", "Charon City", "Uranian Colony","Saturnian", "Deep Space #n##n#."],
"sickness" : ["sickness", "virus", "bacterium", "plague", "prion", "memetic virus", "memevirus"],
"can" :["can", "may"],
"word":["#phon#","#phon##v1#","#phon##word#","#word#ix", "#phon#phon"],
"phon":["#v1##c1##v1##c1#","#c1##v1##c1#"],
	"v1" : ["a","i","u","e","o","","ae","y","oo"], "c1":["q","w","r","t","y","p","s","d","f","g","h","j","k","l","z","x","c","v","b","n","m","","ph","ng","gn","th","ch","kh","sh","ø","î","û","!","△"],
	"definition" : [
"A #type# of #noun# that is #adjs# and #adjs#.  It needs #n# #timeunit#s to #verb#.",
"A #type# of #adjs# #noun# that #can# #verb#.",
"To #verb# #noun#.",
"To #verb# #noun#.",
"To #verb# #noun#.",
"To #verb#.",
"On #noun#.",
"Regarding #noun#.",
"#adjs# #noun#.",
"Synonym for '#noun#'.",
"Equivalent to '#noun#'.",
"Equivalent to the old English '#noun#'.",
"A #sickness# that #can# #verb# the #adjs# #noun#.",
"To #verb# the #adjs# #noun#.",
"To #verb# for #noun#.",
"To #verb# in #noun#.",
"Of pertaining to #noun#.",
"A #type# of #adjs# #noun#.",
"#n# #timeunit#s before #noun#",
"Antonym to '#noun#'.",
"Antonym to '#verb#'.",
"#n# #timeunit#s",
"Of pertaining to #adjs# #noun#.",
"A #type# of #noun#.",
"#n# #timeunit#s after #noun#",
"Antonym to #adjs# '#noun#.'",
"Synonym to '#verb#'.",
"Less than #n# #timeunit#s",
"More than #n# #timeunit#s",

"The #type# of #noun# that is #adjs# and #adjs#.  It needs #n# #timeunit#s to #verb#.",
"The #type# of #adjs# #noun# that #can# #verb#.",
"To #verb# #noun#.",
"To #verb# #noun#.",
"To #verb# #noun#.",
"To #verb#.",
"On the #noun#.",
"Regarding the #noun#.",
"#adjs# #noun#.",
"Synonym for '#noun#'.",
"'#noun#'-equivalent.",
"Equivalent to the old English '#noun#'.",
"A #sickness# that #can# #verb# the #adjs# #noun#.",
"To #verb# the #adjs# #noun#.",
"To #verb# for #noun#.",
"To #verb# in #noun#.",
"Of pertaining to #noun#.",
"A #type# of #adjs# #noun#.",
"#n# #timeunit#s before #noun#",
"Antonym of '#noun#'.",
"Antonym of '#verb#'.",
"#n# #timeunit#s",
"Pertaining to #adjs# #noun#.",
"A certain #type# of #noun#.",
"#n# #timeunit#s before #noun#",
"Antonym of '#adjs# #noun#'.",
"Synonym of '#verb#'.",
"Slightly less than #n# #timeunit#s",
"Slightly more than #n# #timeunit#s",
"A region in #country#.",
"A river in #country#.",
"A crater in #country#.",
"A dome city in #country#.",
"A nanofacility in #country#.",
"Another word for the number #n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n##n#.",
"#definition# #definition#"

],
"type":["kind","type","form", "variation"],
"n": ["2","3","4","5","6","7","8","9","0"],
"timeunit": [
    "nanosecond",
    "microsecond",
    "millisecond",
    "second",
    "minute",
    "hour",
    "day",
    "week",
    "month",
    "year",
    "decade",
    "centurie",
    "millenium"
  ],

    "verb": [
        "accelerate",
        "acclimatize",
        "acculturate",
        "acidify",
        "activate",
        "align",
        "asphyxiate",
        "attach",
        "awaken",
        "bake",
        "bend",
        "bifurcate",
        "blacken",
        "bleed",
        "boast",
        "boil",
        "bounce",
        "break",
        "brighten",
        "broaden",
        "bruise",
        "burn",
        "burst",
        "bust",
        "change",
        "char",
        "choke",
        "clarify",
        "clear",
        "clink",
        "clog",
        "close",
        "collapse",
        "combine",
        "compile",
        "connect",
        "contort",
        "cook",
        "corrode",
        "count",
        "crack",
        "crash",
        "crumble",
        "crumple",
        "crystallize",
        "dampen",
        "darken",
        "deactivate",
        "deaden",
        "decelerate",
        "decrease",
        "deepen",
        "deflate",
        "deform",
        "dent",
        "deploy",
        "derail",
        "despawn",
        "deteriorate",
        "detonate",
        "dilate",
        "dim",
        "distill",
        "distort",
        "dock",
        "download",
        "drag",
        "drain",
        "drill",
        "drive",
        "drop",
        "drown",
        "dry",
        "duplicate",
        "eat",
        "eject",
        "empty",
        "end",
        "entwine",
        "erase",
        "erode",
        "escalate",
        "expand",
        "exsanguinate",
        "factor",
        "fail",
        "fatten",
        "fill",
        "fire",
        "flash",
        "flatten",
        "flip",
        "float",
        "flood",
        "flunk",
        "flush",
        "fly",
        "fold",
        "fracture",
        "freeze",
        "freshen",
        "fry",
        "gather",
        "glide",
        "graduate",
        "grieve",
        "grow",
        "halt",
        "halve",
        "hang",
        "harden",
        "harmonize",
        "hasten",
        "heal",
        "honk",
        "hurt",
        "hush",
        "ignite",
        "improve",
        "increase",
        "inflame",
        "inflate",
        "ionize",
        "jam",
        "land",
        "launch",
        "lean",
        "lengthen",
        "lessen",
        "lighten",
        "liquify",
        "lock",
        "loosen",
        "lower",
        "madden",
        "march",
        "melt",
        "mend",
        "merge",
        "mix",
        "moisten",
        "move",
        "open",
        "operate",
        "orientate",
        "overtire",
        "overtrain",
        "overwork",
        "park",
        "pass",
        "play",
        "plunge",
        "pop",
        "quicken",
        "quiet",
        "quieten",
        "radiate",
        "raise",
        "rattle",
        "reboot",
        "redden",
        "regrow",
        "rejuvenate",
        "reload",
        "relocate",
        "rest",
        "resuscitate",
        "reverse",
        "revert",
        "revive",
        "rewind",
        "ripen",
        "roast",
        "rock",
        "roll",
        "rotate",
        "rouse",
        "run",
        "rupture",
        "rush",
        "rustle",
        "sadden",
        "sail",
        "scatter",
        "scorch",
        "scramble",
        "scroll",
        "sell",
        "separate",
        "shake",
        "shatter",
        "shift",
        "shine",
        "shorten",
        "shrink",
        "shut",
        "sicken",
        "simplify",
        "sink",
        "skip",
        "slam",
        "slant",
        "slide",
        "slow",
        "smash",
        "smear",
        "soak",
        "soften",
        "spawn",
        "spill",
        "spin",
        "splash",
        "splatter",
        "splinter",
        "split",
        "start",
        "starve",
        "steer",
        "stew",
        "stick",
        "stiffen",
        "stir",
        "stop",
        "straighten",
        "strangle",
        "strengthen",
        "stretch",
        "suffocate",
        "sway",
        "sweep",
        "sweeten",
        "swing",
        "tangle",
        "tauten",
        "tear",
        "teleport",
        "terminate",
        "thaw",
        "thicken",
        "thrill",
        "tighten",
        "tip",
        "tire",
        "toast",
        "toll",
        "toot",
        "topple",
        "toughen",
        "train",
        "transfer",
        "transform",
        "turn",
        "twist",
        "twitch",
        "unbend",
        "unbutton",
        "unclog",
        "uncrumple",
        "unfasten",
        "unfurl",
        "unload",
        "unlock",
        "unravel",
        "unroll",
        "untangle",
        "untwist",
        "unwind",
        "unzip",
        "upload",
        "vaporize",
        "waft",
        "wake",
        "weaken",
        "weary",
        "whiten",
        "widen",
        "wilt",
        "wind",
        "worry",
        "worsen"
    ],

  "noun":
    [ "Armour",
      "Barrymore",
      "Cabot",
      "Catholicism",
      "Chihuahua",
      "Christianity",
      "Easter",
      "Frenchman",
      "Lowry",
      "Mayer",
      "Orientalism",
      "Pharaoh",
      "Pueblo",
      "Pullman",
      "Rodeo",
      "Saturday",
      "Sister",
      "Snead",
      "Syrah",
      "Tuesday",
      "Woodward",
      "abbey",
      "absence",
      "absorption",
      "abstinence",
      "absurdity",
      "abundance",
      "acceptance",
      "accessibility",
      "accommodation",
      "accomplice",
      "accountability",
      "accounting",
      "accreditation",
      "accuracy",
      "acquiescence",
      "acreage",
      "actress",
      "actuality",
      "adage",
      "adaptation",
      "adherence",
      "adjustment",
      "adoption",
      "adultery",
      "advancement",
      "advert",
      "advertisement",
      "advertising",
      "advice",
      "aesthetics",
      "affinity",
      "aggression",
      "agriculture",
      "aircraft",
      "airtime",
      "allegation",
      "allegiance",
      "allegory",
      "allergy",
      "allies",
      "alligator",
      "allocation",
      "allotment",
      "altercation",
      "ambulance",
      "ammonia",
      "anatomy",
      "anemia",
      "ankle",
      "announcement",
      "annoyance",
      "annuity",
      "anomaly",
      "anthropology",
      "anxiety",
      "apartheid",
      "apologise",
      "apostle",
      "apparatus",
      "appeasement",
      "appellation",
      "appendix",
      "applause",
      "appointment",
      "appraisal",
      "archery",
      "archipelago",
      "architecture",
      "ardor",
      "arrears",
      "arrow",
      "artisan",
      "artistry",
      "ascent",
      "assembly",
      "assignment",
      "association",
      "asthma",
      "atheism",
      "attacker",
      "attraction",
      "attractiveness",
      "auspices",
      "authority",
      "avarice",
      "aversion",
      "aviation",
      "babbling",
      "backlash",
      "baker",
      "ballet",
      "balls",
      "banjo",
      "baron",
      "barrier",
      "barrister",
      "bases",
      "basin",
      "basis",
      "battery",
      "battling",
      "bedtime",
      "beginner",
      "begun",
      "bending",
      "bicycle",
      "billing",
      "bingo",
      "biography",
      "biology",
      "birthplace",
      "blackberry",
      "blather",
      "blossom",
      "boardroom",
      "boasting",
      "bodyguard",
      "boldness",
      "bomber",
      "bondage",
      "bonding",
      "bones",
      "bonus",
      "bookmark",
      "boomer",
      "booty",
      "bounds",
      "bowling",
      "brainstorming",
      "breadth",
      "breaker",
      "brewer",
      "brightness",
      "broccoli",
      "broth",
      "brotherhood",
      "browsing",
      "brunch",
      "brunt",
      "building",
      "bullion",
      "bureaucracy",
      "burglary",
      "buyout",
      "by-election",
      "cabal",
      "cabbage",
      "calamity",
      "campaign",
      "canonization",
      "captaincy",
      "carcass",
      "carrier",
      "cartridge",
      "cassette",
      "catfish",
      "caught",
      "celebrity",
      "cemetery",
      "certainty",
      "certification",
      "charade",
      "chasm",
      "check-in",
      "cheerleader",
      "cheesecake",
      "chemotherapy",
      "chili",
      "china",
      "chivalry",
      "cholera",
      "cilantro",
      "circus",
      "civilisation",
      "civility",
      "clearance",
      "clearing",
      "clerk",
      "climber",
      "closeness",
      "clothing",
      "clutches",
      "coaster",
      "coconut",
      "coding",
      "collaborator",
      "colleague",
      "college",
      "collision",
      "colors",
      "combustion",
      "comedian",
      "comer",
      "commander",
      "commemoration",
      "commenter",
      "commissioner",
      "commune",
      "competition",
      "completeness",
      "complexity",
      "computing",
      "comrade",
      "concur",
      "condominium",
      "conduit",
      "confidant",
      "configuration",
      "confiscation",
      "conflagration",
      "conflict",
      "consist",
      "consistency",
      "consolidation",
      "conspiracy",
      "constable",
      "consul",
      "consultancy",
      "contentment",
      "contents",
      "contractor",
      "conversation",
      "cornerstone",
      "corpus",
      "correlation",
      "councilman",
      "counselor",
      "countdown",
      "countryman",
      "coverage",
      "covering",
      "coyote",
      "cracker",
      "creator",
      "criminality",
      "crocodile",
      "cropping",
      "cross-examination",
      "crossover",
      "crossroads",
      "culprit",
      "cumin",
      "curator",
      "curfew",
      "cursor",
      "custard",
      "cutter",
      "cyclist",
      "cyclone",
      "cylinder",
      "cynicism",
      "daddy",
      "damsel",
      "darkness",
      "dawning",
      "daybreak",
      "dealing",
      "dedication",
      "deduction",
      "defection",
      "deference",
      "deficiency",
      "definition",
      "deflation",
      "degeneration",
      "delegation",
      "delicacy",
      "delirium",
      "deliverance",
      "demeanor",
      "demon",
      "demonstration",
      "denomination",
      "dentist",
      "departure",
      "depletion",
      "depression",
      "designation",
      "despotism",
      "detention",
      "developer",
      "devolution",
      "dexterity",
      "diagnosis",
      "dialect",
      "differentiation",
      "digger",
      "digress",
      "dioxide",
      "diploma",
      "disability",
      "disarmament",
      "discord",
      "discovery",
      "dishonesty",
      "dismissal",
      "disobedience",
      "dispatcher",
      "disservice",
      "distribution",
      "distributor",
      "diver",
      "diversity",
      "docking",
      "dollar",
      "dominance",
      "domination",
      "dominion",
      "donkey",
      "doorstep",
      "doorway",
      "dossier",
      "downside",
      "drafting",
      "drank",
      "drilling",
      "driver",
      "drumming",
      "drunkenness",
      "duchess",
      "ducking",
      "dugout",
      "dumps",
      "dwelling",
      "dynamics",
      "eagerness",
      "earnestness",
      "earnings",
      "eater",
      "editor",
      "effectiveness",
      "electricity",
      "elements",
      "eloquence",
      "emancipation",
      "embodiment",
      "embroidery",
      "emperor",
      "employment",
      "encampment",
      "enclosure",
      "encouragement",
      "endangerment",
      "enlightenment",
      "enthusiasm",
      "environment",
      "environs",
      "envoy",
      "epilepsy",
      "equation",
      "equator",
      "error",
      "espionage",
      "estimation",
      "evacuation",
      "exaggeration",
      "examination",
      "exclamation",
      "expediency",
      "exploitation",
      "extinction",
      "eyewitness",
      "falls",
      "fascism",
      "fastball",
      "feces",
      "feedback",
      "ferocity",
      "fertilization",
      "fetish",
      "finale",
      "firing",
      "fixing",
      "flashing",
      "flask",
      "flora",
      "fluke",
      "folklore",
      "follower",
      "foothold",
      "footing",
      "forefinger",
      "forefront",
      "forgiveness",
      "formality",
      "formation",
      "formula",
      "foyer",
      "fragmentation",
      "framework",
      "fraud",
      "freestyle",
      "frequency",
      "friendliness",
      "fries",
      "frigate",
      "fulfillment",
      "function",
      "functionality",
      "fundraiser",
      "fusion",
      "futility",
      "gallantry",
      "gallery",
      "genesis",
      "genitals",
      "girlfriend",
      "glamour",
      "glitter",
      "glucose",
      "google",
      "grandeur",
      "grappling",
      "greens",
      "gridlock",
      "grocer",
      "groundwork",
      "grouping",
      "gunman",
      "gusto",
      "habitation",
      "hacker",
      "hallway",
      "hamburger",
      "hammock",
      "handling",
      "hands",
      "handshake",
      "happiness",
      "hardship",
      "headcount",
      "header",
      "headquarters",
      "heads",
      "headset",
      "hearth",
      "hearts",
      "heath",
      "hegemony",
      "height",
      "hello",
      "helper",
      "helping",
      "helplessness",
      "hierarchy",
      "hoarding",
      "hockey",
      "homeland",
      "homer",
      "honesty",
      "horror",
      "horseman",
      "hostility",
      "housing",
      "humility",
      "hurricane",
      "iceberg",
      "ignition",
      "illness",
      "illustration",
      "illustrator",
      "immunity",
      "immunization",
      "imperialism",
      "imprisonment",
      "inaccuracy",
      "inaction",
      "inactivity",
      "inauguration",
      "indecency",
      "indicator",
      "inevitability",
      "infamy",
      "infiltration",
      "influx",
      "iniquity",
      "innocence",
      "innovation",
      "insanity",
      "inspiration",
      "instruction",
      "instructor",
      "insurer",
      "interact",
      "intercession",
      "intercourse",
      "intermission",
      "interpretation",
      "intersection",
      "interval",
      "intolerance",
      "intruder",
      "invasion",
      "investment",
      "involvement",
      "irrigation",
      "iteration",
      "jenny",
      "jogging",
      "jones",
      "joseph",
      "juggernaut",
      "juncture",
      "jurisprudence",
      "juror",
      "kangaroo",
      "kingdom",
      "knocking",
      "laborer",
      "larceny",
      "laurels",
      "layout",
      "leadership",
      "leasing",
      "legislation",
      "leopard",
      "liberation",
      "licence",
      "lifeblood",
      "lifeline",
      "ligament",
      "lighting",
      "likeness",
      "line-up",
      "lineage",
      "liner",
      "lineup",
      "liquidation",
      "listener",
      "literature",
      "litigation",
      "litre",
      "loathing",
      "locality",
      "lodging",
      "logic",
      "longevity",
      "lookout",
      "lordship",
      "lustre",
      "ma'am",
      "machinery",
      "madness",
      "magnificence",
      "mahogany",
      "mailing",
      "mainframe",
      "maintenance",
      "majority",
      "manga",
      "mango",
      "manifesto",
      "mantra",
      "manufacturer",
      "maple",
      "martin",
      "martyrdom",
      "mathematician",
      "matrix",
      "matron",
      "mayhem",
      "mayor",
      "means",
      "meantime",
      "measurement",
      "mechanics",
      "mediator",
      "medics",
      "melodrama",
      "memory",
      "mentality",
      "metaphysics",
      "method",
      "metre",
      "miner",
      "mirth",
      "misconception",
      "misery",
      "mishap",
      "misunderstanding",
      "mobility",
      "molasses",
      "momentum",
      "monarchy",
      "monument",
      "morale",
      "mortality",
      "motto",
      "mouthful",
      "mouthpiece",
      "mover",
      "movie",
      "mowing",
      "murderer",
      "musician",
      "mutation",
      "mythology",
      "narration",
      "narrator",
      "nationality",
      "negligence",
      "neighborhood",
      "neighbour",
      "nervousness",
      "networking",
      "nexus",
      "nightmare",
      "nobility",
      "nobody",
      "noodle",
      "normalcy",
      "notification",
      "nourishment",
      "novella",
      "nucleus",
      "nuisance",
      "nursery",
      "nutrition",
      "nylon",
      "oasis",
      "obscenity",
      "obscurity",
      "observer",
      "offense",
      "onslaught",
      "operation",
      "opportunity",
      "opposition",
      "oracle",
      "orchestra",
      "organisation",
      "organizer",
      "orientation",
      "originality",
      "ounce",
      "outage",
      "outcome",
      "outdoors",
      "outfield",
      "outing",
      "outpost",
      "outset",
      "overseer",
      "owner",
      "oxygen",
      "pairing",
      "panther",
      "paradox",
      "parliament",
      "parsley",
      "parson",
      "passenger",
      "pasta",
      "patchwork",
      "pathos",
      "patriotism",
      "pendulum",
      "penguin",
      "permission",
      "persona",
      "perusal",
      "pessimism",
      "peter",
      "philosopher",
      "phosphorus",
      "phrasing",
      "physique",
      "piles",
      "plateau",
      "playing",
      "plaza",
      "plethora",
      "plurality",
      "pneumonia",
      "pointer",
      "poker",
      "policeman",
      "polling",
      "poster",
      "posterity",
      "posting",
      "postponement",
      "potassium",
      "pottery",
      "poultry",
      "pounding",
      "pragmatism",
      "precedence",
      "precinct",
      "preoccupation",
      "pretense",
      "priesthood",
      "prisoner",
      "privacy",
      "probation",
      "proceeding",
      "proceedings",
      "processing",
      "processor",
      "progression",
      "projection",
      "prominence",
      "propensity",
      "prophecy",
      "prorogation",
      "prospectus",
      "protein",
      "prototype",
      "providence",
      "provider",
      "provocation",
      "proximity",
      "puberty",
      "publicist",
      "publicity",
      "publisher",
      "pundit",
      "putting",
      "quantity",
      "quart",
      "quilting",
      "quorum",
      "racism",
      "radiance",
      "ralph",
      "rancher",
      "ranger",
      "rapidity",
      "rapport",
      "ratification",
      "rationality",
      "reaction",
      "reader",
      "reassurance",
      "rebirth",
      "receptor",
      "recipe",
      "recognition",
      "recourse",
      "recreation",
      "rector",
      "recurrence",
      "redemption",
      "redistribution",
      "redundancy",
      "refinery",
      "reformer",
      "refrigerator",
      "regularity",
      "regulator",
      "reinforcement",
      "reins",
      "reinstatement",
      "relativism",
      "relaxation",
      "rendition",
      "repayment",
      "repentance",
      "repertoire",
      "repository",
      "republic",
      "reputation",
      "resentment",
      "residency",
      "resignation",
      "restaurant",
      "resurgence",
      "retailer",
      "retention",
      "retirement",
      "reviewer",
      "riches",
      "righteousness",
      "roadblock",
      "robber",
      "rocks",
      "rubbing",
      "runoff",
      "saloon",
      "salvation",
      "sarcasm",
      "saucer",
      "savior",
      "scarcity",
      "scenario",
      "scenery",
      "schism",
      "scholarship",
      "schoolboy",
      "schooner",
      "scissors",
      "scolding",
      "scooter",
      "scouring",
      "scrimmage",
      "scrum",
      "seating",
      "sediment",
      "seduction",
      "seeder",
      "seizure",
      "self-confidence",
      "self-control",
      "self-respect",
      "semicolon",
      "semiconductor",
      "semifinal",
      "senator",
      "sending",
      "serenity",
      "seriousness",
      "servitude",
      "sesame",
      "setup",
      "sewing",
      "sharpness",
      "shaving",
      "shoplifting",
      "shopping",
      "siding",
      "simplicity",
      "simulation",
      "sinking",
      "skate",
      "sloth",
      "slugger",
      "snack",
      "snail",
      "snapshot",
      "snark",
      "soccer",
      "solemnity",
      "solicitation",
      "solitude",
      "somewhere",
      "sophistication",
      "sorcery",
      "souvenir",
      "spaghetti",
      "specification",
      "specimen",
      "specs",
      "spectacle",
      "spectre",
      "speculation",
      "sperm",
      "spoiler",
      "squad",
      "squid",
      "staging",
      "stagnation",
      "staircase",
      "stairway",
      "stamina",
      "standpoint",
      "standstill",
      "stanza",
      "statement",
      "stillness",
      "stimulus",
      "stocks",
      "stole",
      "stoppage",
      "storey",
      "storyteller",
      "stylus",
      "subcommittee",
      "subscription",
      "subsidy",
      "suburb",
      "success",
      "sufferer",
      "supposition",
      "suspension",
      "sweater",
      "sweepstakes",
      "swimmer",
      "syndrome",
      "synopsis",
      "syntax",
      "system",
      "tablespoon",
      "taker",
      "tavern",
      "technology",
      "telephony",
      "template",
      "tempo",
      "tendency",
      "tendon",
      "terrier",
      "terror",
      "terry",
      "theater",
      "theology",
      "therapy",
      "thicket",
      "thoroughfare",
      "threshold",
      "thriller",
      "thunderstorm",
      "ticker",
      "tiger",
      "tights",
      "to-day",
      "tossing",
      "touchdown",
      "tourist",
      "tourney",
      "toxicity",
      "tracing",
      "tractor",
      "translation",
      "transmission",
      "transmitter",
      "trauma",
      "traveler",
      "treadmill",
      "trilogy",
      "trout",
      "tuning",
      "twenties",
      "tycoon",
      "tyrant",
      "ultimatum",
      "underdog",
      "underwear",
      "unhappiness",
      "unification",
      "university",
      "uprising",
      "vaccination",
      "validity",
      "vampire",
      "vanguard",
      "variation",
      "vegetation",
      "verification",
      "viability",
      "vicinity",
      "victory",
      "viewpoint",
      "villa",
      "vindication",
      "violation",
      "vista",
      "vocalist",
      "vogue",
      "volcano",
      "voltage",
      "vomiting",
      "vulnerability",
      "waistcoat",
      "waitress",
      "wardrobe",
      "warmth",
      "watchdog",
      "wealth",
      "weariness",
      "whereabouts",
      "whisky",
      "whiteness",
      "widget",
      "width",
      "windfall",
      "wiring",
      "witchcraft",
      "withholding",
      "womanhood",
      "words",
      "workman",
      "youngster" ],
  "adjs":
    [ "Aristotelian",
      "Arthurian",
      "Bohemian",
      "Brethren",
      "Mosaic",
      "Oceanic",
      "Proctor",
      "Terran",
      "Tudor",
      "abroad",
      "absorbing",
      "abstract",
      "academic",
      "accelerated",
      "accented",
      "accountant",
      "acquainted",
      "acute",
      "addicting",
      "addictive",
      "adjustable",
      "admired",
      "adult",
      "adverse",
      "advised",
      "aerosol",
      "afraid",
      "aggravated",
      "aggressive",
      "agreeable",
      "alienate",
      "aligned",
      "all-round",
      "alleged",
      "almond",
      "alright",
      "altruistic",
      "ambient",
      "ambivalent",
      "amiable",
      "amino",
      "amorphous",
      "amused",
      "anatomical",
      "ancestral",
      "angelic",
      "angrier",
      "answerable",
      "antiquarian",
      "antiretroviral",
      "appellate",
      "applicable",
      "apportioned",
      "approachable",
      "appropriated",
      "archer",
      "aroused",
      "arrested",
      "assertive",
      "assigned",
      "athletic",
      "atrocious",
      "attained",
      "authoritarian",
      "autobiographical",
      "avaricious",
      "avocado",
      "awake",
      "awsome",
      "backstage",
      "backwoods",
      "balding",
      "bandaged",
      "banded",
      "banned",
      "barreled",
      "battle",
      "beaten",
      "begotten",
      "beguiled",
      "bellied",
      "belted",
      "beneficent",
      "besieged",
      "betting",
      "big-money",
      "biggest",
      "biochemical",
      "bipolar",
      "blackened",
      "blame",
      "blessed",
      "blindfolded",
      "bloat",
      "blocked",
      "blooded",
      "blue-collar",
      "blushing",
      "boastful",
      "bolder",
      "bolstered",
      "bonnie",
      "bored",
      "boundary",
      "bounded",
      "bounding",
      "branched",
      "brawling",
      "brazen",
      "breeding",
      "bridged",
      "brimming",
      "brimstone",
      "broadest",
      "broiled",
      "broker",
      "bronze",
      "bruising",
      "buffy",
      "bullied",
      "bungling",
      "burial",
      "buttery",
      "candied",
      "canonical",
      "cantankerous",
      "cardinal",
      "carefree",
      "caretaker",
      "casual",
      "cathartic",
      "causal",
      "chapel",
      "characterized",
      "charcoal",
      "cheeky",
      "cherished",
      "chipotle",
      "chirping",
      "chivalrous",
      "circumstantial",
      "civic",
      "civil",
      "civilised",
      "clanking",
      "clapping",
      "claptrap",
      "classless",
      "cleansed",
      "cleric",
      "cloistered",
      "codified",
      "colloquial",
      "colour",
      "combat",
      "combined",
      "comely",
      "commissioned",
      "commonplace",
      "commuter",
      "commuting",
      "comparable",
      "complementary",
      "compromising",
      "conceding",
      "concentrated",
      "conceptual",
      "conditioned",
      "confederate",
      "confident",
      "confidential",
      "confining",
      "confuse",
      "congressional",
      "consequential",
      "conservative",
      "constituent",
      "contaminated",
      "contemporaneous",
      "contraceptive",
      "convertible",
      "convex",
      "cooked",
      "coronary",
      "corporatist",
      "correlated",
      "corroborated",
      "cosmic",
      "cover",
      "crash",
      "crypto",
      "culminate",
      "cushioned",
      "dandy",
      "dashing",
      "dazzled",
      "decreased",
      "decrepit",
      "dedicated",
      "defaced",
      "defective",
      "defenseless",
      "deluded",
      "deodorant",
      "departed",
      "depress",
      "designing",
      "despairing",
      "destitute",
      "detective",
      "determined",
      "devastating",
      "deviant",
      "devilish",
      "devoted",
      "diagonal",
      "dictated",
      "didactic",
      "differentiated",
      "diffused",
      "dirtier",
      "disabling",
      "disconnected",
      "discovered",
      "disdainful",
      "diseased",
      "disfigured",
      "disheartened",
      "disheveled",
      "disillusioned",
      "disparate",
      "dissident",
      "doable",
      "doctrinal",
      "doing",
      "dotted",
      "double-blind",
      "downbeat",
      "dozen",
      "draining",
      "draught",
      "dread",
      "dried",
      "dropped",
      "dulled",
      "duplicate",
      "eaten",
      "echoing",
      "economical",
      "elaborated",
      "elastic",
      "elective",
      "electoral",
      "elven",
      "embryo",
      "emerald",
      "emergency",
      "emissary",
      "emotional",
      "employed",
      "enamel",
      "encased",
      "encrusted",
      "endangered",
      "engraved",
      "engrossing",
      "enlarged",
      "enlisted",
      "enlivened",
      "ensconced",
      "entangled",
      "enthralling",
      "entire",
      "envious",
      "eradicated",
      "eroded",
      "esoteric",
      "essential",
      "evaporated",
      "ever-present",
      "evergreen",
      "everlasting",
      "exacting",
      "exasperated",
      "excess",
      "exciting",
      "executable",
      "existent",
      "exonerated",
      "exorbitant",
      "exponential",
      "export",
      "extraordinary",
      "exultant",
      "exulting",
      "facsimile",
      "fading",
      "fainter",
      "faith-based",
      "fallacious",
      "faltering",
      "famous",
      "fancier",
      "fast-growing",
      "fated",
      "favourable",
      "fearless",
      "feathered",
      "fellow",
      "fermented",
      "ferocious",
      "fiddling",
      "filling",
      "firmer",
      "fitted",
      "flammable",
      "flawed",
      "fledgling",
      "fleshy",
      "flexible",
      "flickering",
      "floral",
      "flowering",
      "flowing",
      "foggy",
      "folic",
      "foolhardy",
      "foolish",
      "footy",
      "forehand",
      "forked",
      "formative",
      "formulaic",
      "foul-mouthed",
      "fractional",
      "fragrant",
      "fraudulent",
      "freakish",
      "freckled",
      "freelance",
      "freight",
      "fresh",
      "fretted",
      "frugal",
      "fulfilling",
      "fuming",
      "funded",
      "funny",
      "garbled",
      "gathered",
      "geologic",
      "geometric",
      "gibberish",
      "gilded",
      "ginger",
      "glare",
      "glaring",
      "gleaming",
      "glorified",
      "glorious",
      "goalless",
      "gold-plated",
      "goody",
      "grammatical",
      "grande",
      "grateful",
      "gratuitous",
      "graven",
      "greener",
      "grinding",
      "grizzly",
      "groaning",
      "grudging",
      "guaranteed",
      "gusty",
      "half-breed",
      "hand-held",
      "handheld",
      "hands-off",
      "hard-pressed",
      "harlot",
      "healing",
      "healthier",
      "healthiest",
      "heart",
      "heart-shaped",
      "heathen",
      "hedonistic",
      "heralded",
      "herbal",
      "high-density",
      "high-performance",
      "high-res",
      "high-yield",
      "hissy",
      "hitless",
      "holiness",
      "homesick",
      "honorable",
      "hooded",
      "hopeless",
      "horrendous",
      "horrible",
      "hot-button",
      "huddled",
      "human",
      "humbling",
      "humid",
      "humiliating",
      "hypnotized",
      "idealistic",
      "idiosyncratic",
      "ignited",
      "illustrated",
      "illustrative",
      "imitated",
      "immense",
      "immersive",
      "immigrant",
      "immoral",
      "impassive",
      "impressionable",
      "improbable",
      "impulsive",
      "in-between",
      "in-flight",
      "inattentive",
      "inbound",
      "inbounds",
      "incalculable",
      "incomprehensible",
      "indefatigable",
      "indigo",
      "indiscriminate",
      "indomitable",
      "inert",
      "inflate",
      "inform",
      "inheriting",
      "injured",
      "injurious",
      "inking",
      "inoffensive",
      "insane",
      "insensible",
      "insidious",
      "insincere",
      "insistent",
      "insolent",
      "insufferable",
      "intemperate",
      "interdependent",
      "interesting",
      "interfering",
      "intern",
      "interpreted",
      "intersecting",
      "intolerable",
      "intolerant",
      "intuitive",
      "irresolute",
      "irritate",
      "jealous",
      "jerking",
      "joining",
      "joint",
      "journalistic",
      "joyful",
      "keyed",
      "knowing",
      "lacklustre",
      "laden",
      "lagging",
      "lamented",
      "laughable",
      "layered",
      "leather",
      "leathern",
      "leery",
      "left-footed",
      "legible",
      "leisure",
      "lessening",
      "liberating",
      "life-size",
      "lifted",
      "lightest",
      "limitless",
      "listening",
      "literary",
      "liver",
      "livid",
      "lobster",
      "locked",
      "long-held",
      "long-lasting",
      "long-running",
      "long-suffering",
      "loudest",
      "loveliest",
      "low-budget",
      "low-carb",
      "lowering",
      "lucid",
      "luckless",
      "lusty",
      "luxurious",
      "magazine",
      "maniac",
      "manmade",
      "maroon",
      "mastered",
      "mated",
      "material",
      "materialistic",
      "meaningful",
      "measuring",
      "mediaeval",
      "medical",
      "meditated",
      "medley",
      "melodic",
      "memorable",
      "memorial",
      "metabolic",
      "metallic",
      "metallurgical",
      "metering",
      "midair",
      "midterm",
      "midway",
      "mighty",
      "migrating",
      "mind-blowing",
      "mind-boggling",
      "minor",
      "mirrored",
      "misguided",
      "misshapen",
      "mitigated",
      "mixed",
      "modernized",
      "molecular",
      "monarch",
      "monastic",
      "morbid",
      "motley",
      "motorized",
      "mounted",
      "multi-million",
      "multidisciplinary",
      "muscled",
      "muscular",
      "muted",
      "mysterious",
      "mythic",
      "nail-biting",
      "natural",
      "nauseous",
      "negative",
      "networked",
      "neurological",
      "neutered",
      "newest",
      "night",
      "nitrous",
      "no-fly",
      "noncommercial",
      "nonsense",
      "north",
      "nuanced",
      "occurring",
      "offensive",
      "oldest",
      "oncoming",
      "one-eyed",
      "one-year",
      "onstage",
      "onward",
      "opaque",
      "open-ended",
      "operating",
      "opportunist",
      "opposing",
      "opt-in",
      "ordinate",
      "outdone",
      "outlaw",
      "outsized",
      "overboard",
      "overheated",
      "oversize",
      "overworked",
      "oyster",
      "paced",
      "panting",
      "paralyzed",
      "paramount",
      "parental",
      "parted",
      "partisan",
      "passive",
      "pastel",
      "patriot",
      "peacekeeping",
      "pedestrian",
      "peevish",
      "penal",
      "penned",
      "pensive",
      "perceptual",
      "perky",
      "permissible",
      "pernicious",
      "perpetuate",
      "perplexed",
      "pervasive",
      "petrochemical",
      "philosophical",
      "picturesque",
      "pillaged",
      "piped",
      "piquant",
      "pitching",
      "plausible",
      "pliable",
      "plumb",
      "politician",
      "polygamous",
      "poorest",
      "portmanteau",
      "posed",
      "positive",
      "possible",
      "postpartum",
      "prank",
      "pre-emptive",
      "precocious",
      "predicted",
      "premium",
      "preparatory",
      "prerequisite",
      "prescient",
      "preserved",
      "presidential",
      "pressed",
      "pressurized",
      "presumed",
      "prewar",
      "priced",
      "pricier",
      "primal",
      "primer",
      "primetime",
      "printed",
      "private",
      "problem",
      "procedural",
      "process",
      "prodigious",
      "professional",
      "programmed",
      "progressive",
      "prolific",
      "promising",
      "promulgated",
      "pronged",
      "proportionate",
      "protracted",
      "pulled",
      "pulsed",
      "purgatory",
      "quick",
      "rapid-fire",
      "raunchy",
      "razed",
      "reactive",
      "readable",
      "realizing",
      "recognised",
      "recovering",
      "recurrent",
      "recycled",
      "redeemable",
      "reflecting",
      "regal",
      "registering",
      "reliable",
      "reminiscent",
      "remorseless",
      "removable",
      "renewable",
      "repeating",
      "repellent",
      "reserve",
      "resigned",
      "respectful",
      "rested",
      "restrict",
      "resultant",
      "retaliatory",
      "retiring",
      "revelatory",
      "reverend",
      "reversing",
      "revolving",
      "ridiculous",
      "right-hand",
      "ringed",
      "risque",
      "robust",
      "roomful",
      "rotating",
      "roused",
      "rubber",
      "run-down",
      "running",
      "runtime",
      "rustling",
      "safest",
      "salient",
      "sanctioned",
      "saute",
      "saved",
      "scandalized",
      "scarlet",
      "scattering",
      "sceptical",
      "scheming",
      "scoundrel",
      "scratched",
      "scratchy",
      "scrolled",
      "seated",
      "second-best",
      "segregated",
      "self-taught",
      "semiautomatic",
      "senior",
      "sensed",
      "sentient",
      "sexier",
      "shadowy",
      "shaken",
      "shaker",
      "shameless",
      "shaped",
      "shiny",
      "shipped",
      "shivering",
      "shoestring",
      "short",
      "short-lived",
      "signed",
      "simplest",
      "simplistic",
      "sizable",
      "skeleton",
      "skinny",
      "skirting",
      "skyrocketed",
      "slamming",
      "slanting",
      "slapstick",
      "sleek",
      "sleepless",
      "sleepy",
      "slender",
      "slimmer",
      "smacking",
      "smokeless",
      "smothered",
      "smouldering",
      "snuff",
      "socialized",
      "solid-state",
      "sometime",
      "sought",
      "spanking",
      "sparing",
      "spattered",
      "specialized",
      "specific",
      "speedy",
      "spherical",
      "spiky",
      "spineless",
      "sprung",
      "squint",
      "stainless",
      "standing",
      "starlight",
      "startled",
      "stately",
      "statewide",
      "stereoscopic",
      "sticky",
      "stimulant",
      "stinky",
      "stoked",
      "stolen",
      "storied",
      "strained",
      "strapping",
      "strengthened",
      "stubborn",
      "stylized",
      "suave",
      "subjective",
      "subjugated",
      "subordinate",
      "succeeding",
      "suffering",
      "summary",
      "sunset",
      "sunshine",
      "supernatural",
      "supervisory",
      "supply-side",
      "surrogate",
      "suspended",
      "suspenseful",
      "swarthy",
      "sweating",
      "sweeping",
      "swinging",
      "swooning",
      "sympathize",
      "synchronized",
      "synonymous",
      "synthetic",
      "tailed",
      "tallest",
      "tangible",
      "tanked",
      "tarry",
      "technical",
      "tectonic",
      "telepathic",
      "tenderest",
      "territorial",
      "testimonial",
      "theistic",
      "thicker",
      "threatening",
      "tight-lipped",
      "timed",
      "timely",
      "timid",
      "torrent",
      "totalled",
      "tougher",
      "traditional",
      "transformed",
      "trapped",
      "traveled",
      "traverse",
      "treated",
      "trial",
      "trunk",
      "trusting",
      "trying",
      "twisted",
      "two-lane",
      "tyrannical",
      "unaided",
      "unassisted",
      "unassuming",
      "unattractive",
      "uncapped",
      "uncomfortable",
      "uncontrolled",
      "uncooked",
      "uncooperative",
      "underground",
      "undersea",
      "undisturbed",
      "unearthly",
      "uneasy",
      "unequal",
      "unfazed",
      "unfinished",
      "unforeseen",
      "unforgivable",
      "unidentified",
      "unimaginative",
      "uninspired",
      "unintended",
      "uninvited",
      "universal",
      "unmasked",
      "unorthodox",
      "unparalleled",
      "unpleasant",
      "unprincipled",
      "unread",
      "unreasonable",
      "unregulated",
      "unreliable",
      "unremitting",
      "unsafe",
      "unsanitary",
      "unsealed",
      "unsuccessful",
      "unsupervised",
      "untimely",
      "unwary",
      "unwrapped",
      "uppity",
      "upstart",
      "useless",
      "utter",
      "valiant",
      "valid",
      "valued",
      "vanilla",
      "vaulting",
      "vaunted",
      "veering",
      "vegetative",
      "vented",
      "verbal",
      "verifying",
      "veritable",
      "versed",
      "vinyl",
      "virgin",
      "visceral",
      "visual",
      "voluptuous",
      "walk-on",
      "wanton",
      "warlike",
      "washed",
      "waterproof",
      "waved",
      "weakest",
      "well-bred",
      "well-chosen",
      "well-informed",
      "wetting",
      "wheeled",
      "whirlwind",
      "widen",
      "widening",
      "willful",
      "willing",
      "winnable",
      "winningest",
      "wireless",
      "wistful",
      "woeful",
      "wooded",
      "woodland",
      "wordless",
      "workable",
      "worldly",
      "worldwide",
      "worst-case",
      "worsted",
      "worthless"],



"country":[
  
     "Afghanistan"
  ,
  
     "Albania"
  ,
  
     "Algeria"
  ,
  
     "American Samoa"
  ,
  
     "Andorra"
  ,
  
     "Angola"
  ,
  
     "Anguilla"
  ,
  
     "Antarctica"
  ,
  
     "Antigua and Barbuda"
  ,
  
     "Argentina"
  ,
  
     "Armenia"
  ,
  
     "Aruba"
  ,
  
     "Australia"
  ,
  
     "Austria"
  ,
  
     "Azerbaijan"
  ,
  
     "Bahamas"
  ,
  
     "Bahrain"
  ,
  
     "Bangladesh"
  ,
  
     "Barbados"
  ,
  
     "Belarus"
  ,
  
     "Belgium"
  ,
  
     "Belize"
  ,
  
     "Benin"
  ,
  
     "Bermuda"
  ,
  
     "Bhutan"
  ,
  
     "Bolivia"
  ,
  
     "Bosnia and Herzegovina"
  ,
  
     "Botswana"
  ,
  
     "Bouvet Island"
  ,
  
     "Brazil"
  ,
  
     "British Indian Ocean Territory"
  ,
  
     "Brunei"
  ,
  
     "Bulgaria"
  ,
  
     "Burkina Faso"
  ,
  
     "Burundi"
  ,
  
     "Cambodia"
  ,
  
     "Cameroon"
  ,
  
     "Canada"
  ,
  
     "Cape Verde"
  ,
  
     "Cayman Islands"
  ,
  
     "Central African Republic"
  ,
  
     "Chad"
  ,
  
     "Chile"
  ,
  
     "China"
  ,
  
     "Christmas Island"
  ,
  
     "Cocos (Keeling) Islands"
  ,
  
     "Colombia"
  ,
  
     "Comoros"
  ,
  
     "Congo"
  ,
  
     "The Democratic Republic of Congo"
  ,
  
     "Cook Islands"
  ,
  
     "Costa Rica"
  ,
  
     "Ivory Coast"
  ,
  
     "Croatia"
  ,
  
     "Cuba"
  ,
  
     "Cyprus"
  ,
  
     "Czech Republic"
  ,
  
     "Denmark"
  ,
  
     "Djibouti"
  ,
  
     "Dominica"
  ,
  
     "Dominican Republic"
  ,
  
     "East Timor"
  ,
  
     "Ecuador"
  ,
  
     "Egypt"
  ,
  
     "England"
  ,
  
     "El Salvador"
  ,
  
     "Equatorial Guinea"
  ,
  
     "Eritrea"
  ,
  
     "Estonia"
  ,
  
     "Ethiopia"
  ,
  
     "Falkland Islands"
  ,
  
     "Faroe Islands"
  ,
  
     "Fiji Islands"
  ,
  
     "Finland"
  ,
  
     "France"
  ,
  
     "French Guiana"
  ,
  
     "French Polynesia"
  ,
  
     "French Southern territories"
  ,
  
     "Gabon"
  ,
  
     "Gambia"
  ,
  
     "Georgia"
  ,
  
     "Germany"
  ,
  
     "Ghana"
  ,
  
     "Gibraltar"
  ,
  
     "Greece"
  ,
  
     "Greenland"
  ,
  
     "Grenada"
  ,
  
     "Guadeloupe"
  ,
  
     "Guam"
  ,
  
     "Guatemala"
  ,
  
     "Guinea"
  ,
  
     "Guinea-Bissau"
  ,
  
     "Guyana"
  ,
  
     "Haiti"
  ,
  
     "Heard Island and McDonald Islands"
  ,
  
     "Holy See (Vatican City State)"
  ,
  
     "Honduras"
  ,
  
     "Hong Kong"
  ,
  
     "Hungary"
  ,
  
     "Iceland"
  ,
  
     "India"
  ,
  
     "Indonesia"
  ,
  
     "Iran"
  ,
  
     "Iraq"
  ,
  
     "Ireland"
  ,
  
     "Israel"
  ,
  
     "Italy"
  ,
  
     "Jamaica"
  ,
  
     "Japan"
  ,
  
     "Jordan"
  ,
  
     "Kazakhstan"
  ,
  
     "Kenya"
  ,
  
     "Kiribati"
  ,
  
     "Kuwait"
  ,
  
     "Kyrgyzstan"
  ,
  
     "Laos"
  ,
  
     "Latvia"
  ,
  
     "Lebanon"
  ,
  
     "Lesotho"
  ,
  
     "Liberia"
  ,
  
     "Libyan Arab Jamahiriya"
  ,
  
     "Liechtenstein"
  ,
  
     "Lithuania"
  ,
  
     "Luxembourg"
  ,
  
     "Macao"
  ,
  
     "North Macedonia"
  ,
  
     "Madagascar"
  ,
  
     "Malawi"
  ,
  
     "Malaysia"
  ,
  
     "Maldives"
  ,
  
     "Mali"
  ,
  
     "Malta"
  ,
  
     "Marshall Islands"
  ,
  
     "Martinique"
  ,
  
     "Mauritania"
  ,
  
     "Mauritius"
  ,
  
     "Mayotte"
  ,
  
     "Mexico"
  ,
  
     "Micronesia, Federated States of"
  ,
  
     "Moldova"
  ,
  
     "Monaco"
  ,
  
     "Mongolia"
  ,
  
     "Montserrat"
  ,
  
     "Morocco"
  ,
  
     "Mozambique"
  ,
  
     "Myanmar"
  ,
  
     "Namibia"
  ,
  
     "Nauru"
  ,
  
     "Nepal"
  ,
  
     "Netherlands"
  ,
  
     "Netherlands Antilles"
  ,
  
     "New Caledonia"
  ,
  
     "New Zealand"
  ,
  
     "Nicaragua"
  ,
  
     "Niger"
  ,
  
     "Nigeria"
  ,
  
     "Niue"
  ,
  
     "Norfolk Island"
  ,
  
     "North Korea"
  ,
  
     "Northern Ireland"
  ,
  
     "Northern Mariana Islands"
  ,
  
     "Norway"
  ,
  
     "Oman"
  ,
  
     "Pakistan"
  ,
  
     "Palau"
  ,
  
     "Palestine"
  ,
  
     "Panama"
  ,
  
     "Papua New Guinea"
  ,
  
     "Paraguay"
  ,
  
     "Peru"
  ,
  
     "Philippines"
  ,
  
     "Pitcairn"
  ,
  
     "Poland"
  ,
  
     "Portugal"
  ,
  
     "Puerto Rico"
  ,
  
     "Qatar"
  ,
  
     "Reunion"
  ,
  
     "Romania"
  ,
  
     "Russian Federation"
  ,
  
     "Rwanda"
  ,
  
     "Saint Helena"
  ,
  
     "Saint Kitts and Nevis"
  ,
  
     "Saint Lucia"
  ,
  
     "Saint Pierre and Miquelon"
  ,
  
     "Saint Vincent and the Grenadines"
  ,
  
     "Samoa"
  ,
  
     "San Marino"
  ,
  
     "Sao Tome and Principe"
  ,
  
     "Saudi Arabia"
  ,
  
     "Scotland"
  ,
  
     "Senegal"
  ,
  
     "Seychelles"
  ,
  
     "Sierra Leone"
  ,
  
     "Singapore"
  ,
  
     "Slovakia"
  ,
  
     "Slovenia"
  ,
  
     "Solomon Islands"
  ,
  
     "Somalia"
  ,
  
     "South Africa"
  ,
  
     "South Georgia and the South Sandwich Islands"
  ,
  
     "South Korea"
  ,
  
     "South Sudan"
  ,
  
     "Spain"
  ,
  
     "SriLanka"
  ,
  
     "Sudan"
  ,
  
     "Suriname"
  ,
  
     "Svalbard and Jan Mayen"
  ,
  
     "Swaziland"
  ,
  
     "Sweden"
  ,
  
     "Switzerland"
  ,
  
     "Syria"
  ,
  
     "Tajikistan"
  ,
  
     "Tanzania"
  ,
  
     "Thailand"
  ,
  
     "Togo"
  ,
  
     "Tokelau"
  ,
  
     "Tonga"
  ,
  
     "Trinidad and Tobago"
  ,
  
     "Tunisia"
  ,
  
     "Turkey"
  ,
  
     "Turkmenistan"
  ,
  
     "Turks and Caicos Islands"
  ,
  
     "Tuvalu"
  ,
  
     "Uganda"
  ,
  
     "Ukraine"
  ,
  
     "United Arab Emirates"
  ,
  
     "United Kingdom"
  ,
  
     "United States"
  ,
  
     "United States Minor Outlying Islands"
  ,
  
     "Uruguay"
  ,
  
     "Uzbekistan"
  ,
  
     "Vanuatu"
  ,
  
     "Venezuela"
  ,
  
     "Vietnam"
  ,
  
     "Virgin Islands"
  ,
  
     "Nusantara"
  ,
  
     "Wales"
  ,
  
     "Wallis and Futuna"
  ,
  
     "Western Sahara"
  ,
  
     "Yemen"
  ,
  
     "Yugoslavia"
  ,
  
     "Zambia"
  ,
  
     "Zimbabwe"
  
]


},

}



